### ISSUE TITLE
Cannot check for file attachments in an email.

### ISSUE THREAD

**Issue by vnimmaevhc** [CynoteckLabs/CTK-Email-Parser-Support#1]
**Describe the bug**
We are using CTK Email Parser version 1.8 in our SF Org. 
We have requirement to check for the attachments in the email.

**To Reproduce**
1. Created Email Parser to extract email contents from Email
2. Created Email Filter 
3. Created Field Parser to extract file attachments
4. Send an email with an attachment to this email server

**Expected behavior**
Parsed Value for file attachment is null

**Screenshots**
Please see the attached file

**Desktop (please complete the following information):**
Windows

**Additional context**
Please set up the call if you can to go over the issue.
[CTK Email Parser_ File Attachment Issue.docx](https://github.com/CynoteckLabs/CTK-Email-Parser-Support/files/15419226/CTK.Email.Parser_.File.Attachment.Issue.docx)

**Comment by toanshulverma** [comment]
Issue is fixed as per release 1.9 (Refer: https://ctkemailparser.com/docs/release-notes/ctk-email-parser-1-9-release/)
